/*
 * @(#)VCREjectButton.java   2009.02.24 at 09:44:54 PST
 *
 * Copyright 2007 MBARI
 *
 * Licensed under the GNU LESSER GENERAL PUBLIC LICENSE, Version 2.1
 * (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.gnu.org/copyleft/lesser.html
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */



/* Generated by Together */
package org.mbari.vcr4j.ui;

/**
 * <p>Eject button for used for the VCR UI</p>
 *
 * @author  : $Author: hohonuuli $
 * @version : $Revision: 3 $
 */
public class VCREjectButton extends VCRButton {

    /**
     *
     */
    private static final long serialVersionUID = -2297084449551870486L;

    /** Constructror */
    public VCREjectButton() {
        super();
        setOnIcon("/images/vcr/eject_r.png");
        setOffIcon("/images/vcr/eject.png");
        setToolTipText("Eject");
    }

    /**
     * This class could be registered to a VCRState object as an observer. However,
     * this is currently an empty method since there are no eject messages supplied by tthe VCR to monitor.
     * @param observed A VCRState Object
     * @param stateChange A message about the change of state.
     */
    public void update(Object observed, Object stateChange) {

        // IVCRManager m = vcr.getVcrManager();
    }

    /**
     * <p><!-- Method description --></p>
     *
     */
    void vcrAction() {
        if (vcr != null) {
            vcr.eject();
        }
    }
}
